<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56308" started-at="2014-11-03T14:09:50Z" finished-at="2014-11-03T14:10:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56308" started-at="2014-11-03T14:09:50Z" finished-at="2014-11-03T14:10:46Z">
      <class name="com.sfdc.scripts.SFDC_AccountVerification">
        <test-method status="PASS" signature="preCondition()[pri:0, instance:com.sfdc.scripts.SFDC_AccountVerification@165391b]" name="preCondition" is-config="true" duration-ms="12455" started-at="2014-11-03T19:39:50Z" finished-at="2014-11-03T19:40:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="FAIL" signature="testSFDC_CreateAccount()[pri:0, instance:com.sfdc.scripts.SFDC_AccountVerification@165391b]" name="testSFDC_CreateAccount" duration-ms="43823" started-at="2014-11-03T19:40:02Z" finished-at="2014-11-03T19:40:46Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Your InputStream was neither an OLE2 stream, nor an OOXML stream]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Your InputStream was neither an OLE2 stream, nor an OOXML stream
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:75)
	at com.sfdc.pom.AccountDetailPage.AccountDetailVerification(AccountDetailPage.java:68)
	at com.sfdc.scripts.SFDC_AccountVerification.testSFDC_CreateAccount(SFDC_AccountVerification.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSFDC_CreateAccount -->
      </class> <!-- com.sfdc.scripts.SFDC_AccountVerification -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
